version: "3.5"

services:
  frontend:
    image: node:14
    expose:
    - "3000"
    ports:
    - "3301:3000"
    command: ["./wait-for-it.sh", "database:5432", "--", "yarn", "run", "server"]
    volumes: 
      - front_vol:/usr/src/app
    environment:
      DATABASE_HOST: database
      DATABASE_PORT: "5432"
    depends_on:
      - database 
      - worker
      #- wordpress
    working_dir: /usr/src/app
    restart: always
    networks:
      - calmness


  worker:
    image: node:14
    expose:
    - "3000"
    ports:
    - "4491:3000"
    command: ["./wait-for-it.sh", "database:5432","--", "yarn", "run:server"]
    volumes: 
       - worker_vol:/usr/src/app
    environment:
      DATABASE_HOST: database
      DATABASE_PORT: "5432"
    depends_on:
      - database
    working_dir: /usr/src/app
    restart: always
    networks:
      - calmness


  storefront:
    image: node:14
    environment: 
      SERVER_API_HOST: http://server
      SERVER_API_PORT: "3000"
      SERVER_API_PATH: shop-api
    expose:
      - "4000"
    ports:
      - "4882:4000"
    restart: always
    networks: 
      - calmness
    depends_on: 
      - frontend


  database: 
    image: postgres:13
    expose:
      - "5432"
    ports:
      - "20996:5432"
    environment: 
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vendure
    volumes: 
      - postgres_data:/var/lib/postgresql/data
    networks: 
      - calmness
    restart: always


  database-replica:
    image:  postgres:13
    expose:
      - "5432"
    ports:
      - "30111:5432"
    environment: 
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vendure
    volumes:
      - postgres_data1:/var/lib/postgresql/data
    networks: 
      - calmness
    restart: always
  

  mariadb:
    image: mariadb
    expose:
      - "5432"
    ports:
      - "1857:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - calmness
    restart: always


  wordpress:
    image: wordpress:4.7-php7.1-apache
    environment:
      MONEI_OPERATION_MODE: live
      MONEI_TEST_CHANNEL_ID: test_channel_id
      MONEI_TEST_USER_ID: test_user_id
      MONEI_TEST_PASSWORD: test_password
      MONEI_LIVE_CHANNEL_ID: live_channel-id
      MONEI_LIVE_USER_ID: live_user_id
      MONEI_LIVE_PASSWORD: live_password
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_SITE_TITLE: some_site_title 
      WORDPRESS_ADMIN_PASSWORD: "1234"
    volumes: 
      - wordpress_data:/var/lib/mysql
      - apache_data:/usr/local/apache2/htdocs/
      - php_data:/var/www/html/
      
    depends_on:
      - mariadb
    expose:
      - "80"
      - "443"
    ports:
      - "30123:80"
      - "20139:443"
    networks:
      - calmness
    restart: always


  redis01:
    image: redis:6.0-alpine
    networks:
      - calmness
    restart: always
    volumes:
      - redis01_data:/data


  redis02:
    image: redis:6.0-alpine
    networks:
      - calmness
    restart: always
    volumes:
      - redis02_data:/data


  redis03:
    image: redis:6.0-alpine
    networks:
      - calmness
    restart: always
    volumes:
      - redis03_data:/data

  redis-sentinel01:
    image: redis:6.0-alpine
    networks:
      - calmness
    volumes:
      - senti01_data:/data
    restart: always
    depends_on:
      - redis01
      - redis02
      - redis03

  redis-sentinel02:
    image: redis:6.0-alpine
    networks:
      - calmness
    volumes:
      - senti02_data:/data
    restart: always
    depends_on:
      - redis01
      - redis02
      - redis03

  redis-sentinel03:
    image: redis:6.0-alpine
    networks:
      - calmness
    volumes:
      - senti03_data:/data
    restart: always
    depends_on:
      - redis01
      - redis02
      - redis03

networks:
  calmness:
    driver: bridge

volumes:
  redis01_data:
    driver: local
  redis02_data:
    driver: local
  redis03_data:
    driver: local
  senti01_data:
    driver: local
  senti02_data:
    driver: local
  senti03_data:
    driver: local
  wordpress_data:
    driver: local
  apache_data:
    driver: local
  php_data:
    driver: local
  mariadb_data:
    driver: local
  postgres_data:
    driver: local
  postgres_data1:
    driver: local
  front_vol:
    driver: local
  worker_vol:
    driver: local






     

    


    

    

  


  



  



