version: '3.5'

services:
  wordpress:
    image: wordpress
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: example
    networks:
      - local

  frontend:
    image: your-frontend-image
    ports:
      - "3000:3000"
    depends_on:
      - wordpress
    networks:
      - local

  worker:
    image: your-worker-image
    depends_on:
      - redis
      - postgres
    networks:
      - local

  storefront:
    image: your-storefront-image
    depends_on:
      - worker
    networks:
      - local

  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example
    networks:
      - local

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
    networks:
      - local

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - local

  redis-sentinel-1:
    image: redis
    command: ["redis-sentinel", "--sentinel announce-ip 127.0.0.1", "--sentinel announce-port 26379"]
    ports:
      - "26379:26379"
    depends_on:
      - redis
    networks:
      - local

  redis-sentinel-2:
    image: redis
    command: ["redis-sentinel", "--sentinel announce-ip 127.0.0.1", "--sentinel announce-port 26380"]
    ports:
      - "26380:26380"
    depends_on:
      - redis
    networks:
      - local

  redis-sentinel-3:
    image: redis
    command: ["redis-sentinel", "--sentinel announce-ip 127.0.0.1", "--sentinel announce-port 26381"]
    ports:
      - "26381:26381"
    depends_on:
      - redis
    networks:
      - local

networks:
  local:
    driver: bridge
