apiVersion: v1
kind: Service
metadata:
  name: momentan-service
spec:
  selector:
    app: momentan
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080 # Change to your application's port
  type: LoadBalancer
