version: '3.3'

services:
  # MySQL database
  wordpress_db:
    image: mysql:5.7
    volumes:
      - wordpress_mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example_root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: example_password

  # WordPress application with version 5.8
  wordpress_app:
    depends_on:
      - wordpress_db
    image: wordpress:5.8
    volumes:
      - wordpress_app_data:/var/www/html
    ports:
      - "8081:80"
    environment:
      WORDPRESS_DB_HOST: wordpress_db
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: example_password
      WORDPRESS_DB_NAME: wordpress
    restart: always

volumes:
  wordpress_mysql_data:
  wordpress_app_data:
